### ISSUE TITLE
Effect Size spm1d.stats.anova1rm

### ISSUE THREAD

**Issue by hauptschueler** [0todd0000/spm1d#118]
Hi,
First of all, thank you for providing such a useful platform.

I'm conducting a repeated-measures ANOVA with n conditions and i participants on time normalized biomechanical data.

I would like to report effect sizes for my data. However, in the forum, I only found information about how to calculated Cohens D. Is there any possibility to calculate effect sizes for rANOVAl either as a continuous variable or as a discrete variable, e.g. maximal effect size.

Thank you so much in advanced

**Comment by 0todd0000** [comment]
Hello!

**spm1d** does not support effect size calculation directly. One reason is that effect sizes can be misleading for 1D data:  there is a relatively high probability that completely random 1D data will produce relatively large effect sizes. There is no theory or guidelines of which I am aware for interpreting 1D effect sizes.

One way to include effect sizes in your analyses is with power analysis. Power analysis theory is much stronger than effect size theory for 1D (and nD) data. Here are some examples of how 1D effect sizes can be modeled and incorporated in power analyses:
http://www.spm1d.org/power1d/Examples/DataSample.html

**spm1d** may support effect size calculations in the future, but for now I'd suggest avoiding them, because 1D effects sizes can be misleading.

Todd
