### ISSUE TITLE
ROI for ttest2 after anova1rm ?

### ISSUE THREAD

**Issue by manu13008** [0todd0000/spm1d#130]
Hello Todd, 

We are performing an spm1d anova1rm on 3 conditions and then a spm1d ttest2 for each pair of conditions (A vs B, B vs C, A vs C).

We are wondering if we should consider all the statistical differences for the ttest2 or only the region where the anova1rm showed statistical difference ? 
For instance, if the anova1rm showed differences only between 20 and  30% of the signal, but the ttest2 showed also statistical differences between 20 and 50%, should we ignore the part after 30% ?

Thanks in advance for your reply

Best regards,

Emmanuel AYAD

**Comment by m-a-robinson** [comment]
Hello Emmanuel,

I believe that previous replies from Todd in the spm1d Matlab forum will address the possible differences between main anova and post-hoc t-test results you see. Note specifically that paired t-tests (spm1d.stats.ttest_paired) are more appropriate post-hoc tests for repeated measures designs.

https://github.com/0todd0000/spm1dmatlab/issues/121#issuecomment-558946866 

_For simple univariate 0D data, it is relatively easy to ensure that all post hoc analyses (e.g. t tests) agree probabilistically with the main test (e.g. one way ANOVA). Maintaining probabilistic consistency between the main and post hoc tests becomes more difficult, and somewhat abstract, for multivariate 0D data. It also becomes difficult for uni-/multivariate 1D data. I am unaware of robust post hoc procedures in the SPM literature which maintain probabilistic consistency between the main and post hoc tests._

_Since spm1d does not not support robust post hoc analysis, it's usually best to regard the main test's outputs as the main results, and arbitrary post hoc analyses as approximate qualifications of that main result._

https://github.com/0todd0000/spm1dmatlab/issues/117#issuecomment-531948981
_Note that anova1_posthoc.m uses two-sample tests (spm1d.stats.ttest2) for post hoc analyses because the design is between-subjects (i.e., not repeated measures - RM). To conduct post hoc analyses on [...] an RM factor, try paired t tests (spm1d.stats.ttest_paired). The results may not agree precisely with the ANOVA results, but they should produce closer results than two-sample tests._
