### ISSUE TITLE
Normality test discrete vs SPM

### ISSUE THREAD

**Issue by AlbertoNTC** [0todd0000/spm1d#135]
Hello. I want to compare a discrete 2-way ANOVA with continuous waveform data SPM 2-way ANOVA too. 

My question is: Do I need to test normality in both discrete and continuous data? Or, for instance, if I test on discrete data, would this be enough for continuous data too?

Finally, Is there an option in SPM for Friedman's test (equivalent to 2-way ANOVA RM for non-parametric data)? 

Thank you, 
-Alberto

**Comment by 0todd0000** [comment]
Hello Alberto,

> Do I need to test normality in both discrete and continuous data? Or, for instance, if I test on discrete data, would this be enough for continuous data too?

It depends what the purpose of the analysis is...
If the goal is to check the distribution, as a marker for parametric test suitability, then passing a discrete test may indeed be suitable. However, since the discrete test does not pertain to the whole continuous domain, it may be safest to also consider normality for the continuous data. I personally think the best strategy is to conduct both parametric and non-parametric analyses, and to compare the results. If the results qualitatively agree, then the parametric approach's assumption of normality is a reasonable one.


> Finally, Is there an option in SPM for Friedman's test (equivalent to 2-way ANOVA RM for non-parametric data)?

There is a non-parametric test for 2-way RM-ANOVA, but it is not Friedman's test. It is instead a permutation test. It is available in: **spm1d.stats.nonparam.anova2rm**

Todd

**Comment by AlbertoNTC** [comment]
Hello Profesor Pataky, 

To double-check I got this right, for the normality test on the continuous data, I would need to conduct both parametric and non-parametric 2-way ANOVA RM, and compare these results (if SnPM{F} inference list and SPM{F} inference list give the same results in accepting or rejecting h0)? 

And another question, What would be the practical difference in interpretation of the non-parametric 2-way ANOVA compared to Friedman's test?

Thank you again for the great support, 
-Alberto

**Comment by 0todd0000** [comment]
> I would need to conduct both parametric and non-parametric 2-way ANOVA RM, and compare these results (if SnPM{F} inference list and SPM{F} inference list give the same results in accepting or rejecting h0)?

Yes, if there is a difference in the null rejection decision this would certainly be a sign that the distribution might be non-normal. You could also compare the threshold heights. The parametric and non-parametric threshold heights are generally different, but if similar clusters emerge then there is little practical difference between the two thresholds for that particular dataset. This implies that, even if the data is non-normal, an assumption of normality has little effect on the interpretation.


> What would be the practical difference in interpretation of the non-parametric 2-way ANOVA compared to Friedman's test?

The Friedman test is a [rank test](https://en.wikipedia.org/wiki/Rank_test), but **spm1d**'s non-parametric test is a [permutation test](https://en.wikipedia.org/wiki/Resampling_(statistics)#Permutation_tests). The practical difference is difficult to say, because it depends on the sample size and nature of the distributions. One potentially practical difference is that different tests tend to have different powers for different sample sizes and effect sizes. Perhaps an indirect answer is: as the data distribution approaches normality, and as the sample size increases, all three types of tests converge to the same answer (parametric, permutation and rank tests). Conversely, as sample size decreases, one needs to be increasingly more cautious when interpreting results because different techniques' results tend to diverge.  See the article below that considers the similarities and differences amongst a variety of non-parametric tests. This is not a very comprehensive article, but still provides a nice summary of the different perspectives of different tests. 
[What's the difference? : An Overview of Non-Parametric Tests](https://miningthedetails.com/blog/r/non-parametric-tests/)

**Comment by AlbertoNTC** [comment]
Thank you very much, Professor Pataky. This has been very helpful.

**Comment by 0todd0000** [comment]
You're welcome!

**Comment by 11mhs** [comment]
Hello, I have a series of joint angle data taken from two control and experimental groups in the pre-test and post-test conditions. What is the normality of the data and how is it analyzed? Can I use post hoc to check the conditions? Should I check the group and between groups to find the difference? What do you think of the appropriate test? Thank you

**Comment by 0todd0000** [comment]
For a two-sample t test a normality test can be conducted using:

```python
results = spm1d.stats.normality.ttest2(yA, yB).inference(alpha)
```

<br>
<br>
<br>

A similar interface exists for all other tests, so if your hypothesis test is conducted using a function called `test_name` as in:

```python
spm1d.stats.test_name
```

then the corresponding normality test can be conducted using:

```
spm1d.stats.normality.test_name
```

<br>
<br>
<br>

Here is a [full example script](https://github.com/0todd0000/spm1d/blob/master/spm1d/examples/normality/1d/ex_ttest2.py) for the two-sample case.

Find more normality examples for additional tests [here](https://github.com/0todd0000/spm1d/tree/master/spm1d/examples/normality).

**Comment by Chamoux74** [comment]
Hi Pr Pataky, 

I I was wondering if it was possible to perform a normality test for a 3-way repeated measures anova

Many thanks
Kind regard 

Maxime

**Comment by 0todd0000** [comment]
Yes, using the same approach above:

```python
spm1d.stats.normality.test_name
```

in this case:

```python
alpha  = 0.05
result = spm1d.stats.normality.anova3rm(y, A, B, C, SUBJ).inference(alpha)
```

**Comment by Chamoux74** [comment]
Thank you very much for your reply and your responsiveness.

In my case, nonparametric analysis requires computational resources that I don't have... Is there another solution?

I can't find any information online; perhaps you can answer my question.

Is the normality test essential for this type of analysis?

Because many studies don't report it...

**Comment by 0todd0000** [comment]
> Is the normality test essential for this type of analysis?

Normality tests are not essential. You can instead check normality indirectly, but separately running parametric analyses and nonparametric analyses. Insofar as the results agree, the parametric approach's assumption of normality is inconsequential.

> nonparametric analysis requires computational resources that I don't have

Nonparametric analysis is somewhat more numerically intensive, but if you can run parametric analysis you should also be able to run nonparametric analysis. Can you please explain why you are unable to run nonparametric analysis?

**Comment by Chamoux74** [comment]
Ok many thanks 

I'm using spm1d in R, via the reticulate package with this code:

anovanonparam <- spm1d$stats$nonparam$anova3rm(Y_py,
                              A = condition_py,   # Condition: PLA/FIR
                              B = timepoint_py,   # Time: baseline/post
                              C = placement_py,   # Location: leg/calf
                              SUBJ = subject_py)

inference_nonparam <- anovanonparam$inference(alpha=0.05)

And when I run anova nonparametric, it gives me this warning message:

Erreur dans py_call_impl(callable, call_args$unnamed, call_args$named) : 
  Warning: 
The total nuumber of permutations (252607574497319842185432046571965025570452915794833303316148551571829881593149111856722675267999046296266387492444937218523375550227752823657610051659488187781107743173548620119811756516937712752428790006487383593211723266456409400059217551600311563345359077546614260827582833230098178165690412256198656) is very large and may cause computational problems. To enable non-parametric calculations for this many iterations set "force_iterations=True" when calling "inference".
NOTE: Setting "force_iterations=True" may require substantial computational resources and may cause crashes. USE WITH CAUTION.
