### ISSUE TITLE
How to calculate Power for SPM tests

### ISSUE THREAD

**Issue by kbsmale** [0todd0000/spm1d#14]
First I'd like to thank you for the v0.3 update. It is greatly appreciated to have access to more tests as a matlab user.

I was just wondering how, if possible, to calculate the power of these different tests? I don't see anything in the provided scripts. If there are no provided power calculations, how correct (or wrong) is it to use the traditional way of taking a discrete time point, finding the effect size at that point and use the critical t and sample size to calculate power. I assume there are issues with this since the critical t is calculated with RFT...

Any help would be greatly appreciated!

-Kenneth

**Comment by 0todd0000** [comment]
Hi Kenneth, thanks very much for your mail, power calculations are definitely important.  As you noticed power calculations are not presently available in **spm1d**, but we plan to make them available in the next major release (summer 2016).  

Computing power at the 1D level is certainly possible and we're actually working on a Technical Note at the moment to explain how.  A key paper which covers this topic is:

Friston, K. J., Holmes, A., Poline, J. B., Price, C. J., & Frith, C. D. (1996). Detecting activations in PET and fMRI: levels of inference and power. NeuroImage, 4(3 Pt 1), 223–235. http://doi.org/10.1006/nimg.1996.0074 

An important concept, which arises in 1D analysis but not in 0D (discrete time point) analysis is that power requires one to define the effect one wishes to detect.  In the 0D case it's trivial because the effect is simply a scalar.  In the 1D case it could be a scalar representing a constant 1D difference, it could be a triangular or square or Gaussian pulse at a particular point in time, or it could be something else altogether.  Thus using a RFT critical value should get you close to an accurate estimate of power, but only for a very specific type of signal.

If you're interested in implementing power analysis just let us know, we'd be keen to discuss and/or collaborate. 

Todd
