### ISSUE TITLE
How to compare a specific subject kinematics curve against a normality standard?

### ISSUE THREAD

**Issue by lmeneg** [0todd0000/spm1d#140]
Dear Colleagues,

Maybe it is a naive question, but my statistics background is not the best one. I want to analyze the effect of tendon transfer surgery on the kinematics of hand fingers. We collected samples of hand joints angles in normal subjects (around 10) performing a cyclic movement, to form a normality reference curve (average +- SD, 0 to 100% of the movement cycle). Then we collected the kinematics of a patient before and after the surgery. We can see that, before the surgery, the joint angle x movement cycle curve is outside the normality range, while after the surgery, it is inside. 

I’m wondering if there is a statistical test to check whether the joint angle curve of a specific subject, in the case our patient, can be said to be inside or outside the normality range. From what I searched, it should be something like a ‘goodness-of-fit’ test. My experience with spm1d is on ttest, but I suppose I could not apply a ttest for this (1 x N subjects).

Can anyone give me any advice if I can use ssp1d to solve this question? I realize that such a test is very useful in any situation regarding the diagnostics of a particular patient kinematics or dynamics against a normality standard, e.g., in gait analysis.

Thanks a lot,

Luciano Menegaldo
Federal University of Rio de Janeiro

**Comment by 0todd0000** [comment]
Dear Luciano,

Are there multiple measurements of the patient's kinematics, both before and after surgery?

The analysis possibilities will change depending on the answer to this question.

First, let's assume "no" (i.e., just one measurement before and after surgery).
* I think the only option in this case is: two one-sample t tests.
* This will compare (1) the Normal group to the before measurement, then (1) the Normal group to the after measurement
* However, it will not be possible to conclude much about this particular patient;  making statistical conclusions regarding an individual requires multiple measurements, so that the individual's variability can be assessed

Second, let's assume "yes".
* There are many different analysis possibilities including paired tests, two-sample tests, etc., so let's discuss these possibilities later if the answer is "yes"

Todd

**Comment by lmeneg** [comment]
Dear Todd,

Thank you very much for your answer!

We have two patients, but with different clinical pictures and surgical techniques. For one of them we have three repetitions with a good kinematics reconstruction before and after the surgery. For the other, two repetitions before and three after the surgery. Correcting my previous message, we have 15 normals.

Regards,

Luciano

**Comment by 0todd0000** [comment]
With just 2-3 measurements it is not possible to accurately estimate variance, so many statistical procedures will not work well. Two separate one-sample t tests might be the only possibility:

1. A one-sample t test comparing (i) the 15 Normals to (ii) mean Before.
1. A one-sample t test comparing (i) the 15 Normals to (ii) mean After.

However, note that these tests are not ideal, because they are actually focussed on the Normal group, and not on the patient. That is, if a test reaches significance, it would imply significance only in the Normal group. This does not necessarily imply that the patient is different from the Normals. To support a patient-specific conclusion, more measurements would be required, both Before and After. Usually 5-10 measurements are required, but more may be necessary if the data follow an odd distribution.

**Comment by lmeneg** [comment]
Thank you very much, Todd.
At this moment, it is not possible to collect more data.  I will try the ttest as you recommended.
Best regards and congratulations for spm1d. It has been extremely useful for several projects I'm involved. 
Luciano
