### ISSUE TITLE
Mean between group differences and 95% CI in ANOVA

### ISSUE THREAD

**Issue by VSGhent** [0todd0000/spm1d#143]
Dear Todd,

I am currently reworking my paper on 3D scapular kinematics and EMG activity during shoulder movements in EDS patients, using SPM. In order to compare groups (3 groups), I performed a one-way independent ANOVA with post hoc analyses of two-sample t tests conducted on all group pairs. A reviewer asked me to report the "mean between group differences" and the "95% CI of these differences". Is it possible to determine the mean difference and 95% CI of the suprathreshold clusters by the use of SPM? 

Thank you in advance,
Valentien Spanhove

**Comment by m-a-robinson** [comment]
Hello 

The reviewer seems to want some indication of certainty/uncertainty for the results and they have suggested the mean difference and 95% CI. You can do this with the spm1d package. For the post-hoc tests instead of presenting the t-statistic outcome you could present the mean group difference and the 95% confidence interval. Where the confidence interval doesn’t include zero then there is a significant difference. The confidence interval will help you interpret the uncertainty of the difference and whether this is beyond your measurement error or a clinically meaningful difference that you should usually pre-determine. 

The [spm1d website](https://spm1d.org/NewFeatures.html#label-confidenceintervals) has examples for calculating the CI – note they are design specific so choose the two-sample one for your design.  

Regards
Mark
