### ISSUE TITLE
one-way repeated measures AVOVA

### ISSUE THREAD

**Issue by meteor77** [0todd0000/spm1d#146]
Hi Todd,

I hope this message finds you well. I have conducted a one-way repeated measures ANOVA. I noticed that the inference level in the example file is calculated for the within-subject model. For the between-subjects model should I replace the "spm" variable in this line of code "spmi = spm.inference(0.05);" with "spm_bs" or does the inference level calculated for the within-subjects model apply to the between-subjects model?

Thank you

**Comment by m-a-robinson** [comment]
Hello,

For the RM ANOVA you do not need the code `spm_bs    = spm1d.stats.anova1(Y, A);  %between-subjects model` this is only for illustrative purposes to show the differences between the models. Therefore the code below is sufficient.

```
spm       = spm1d.stats.anova1rm(Y, A, SUBJ);  %within-subjects model
spmi      = spm.inference(0.05);
disp(spmi)

Regards
Mark 
```

**Comment by meteor77** [comment]
Thank you Mark for the quick reply.

So in the case when I plot the graph (both the within-subjects and between-subjects models) what is the within-subjects model doesn't surpass the threshold and the between-subject model does?

**Comment by m-a-robinson** [comment]
As you are only interested in the within subjects model this is the only one that you should use the address your hypothesis.
Mark

**Comment by meteor77** [comment]
And I assume that for the between-subjects model I would have to use anova1.m. Am I correct in saying that?

Shahab

**Comment by m-a-robinson** [comment]
Yes that's correct.

**Comment by meteor77** [comment]
Thank you again.
Just one more question.
For the repeated measures one-way ANOVA we typically have multiple measurements for each subject (10 per each case in our study) thus we used the anova1rm and we calculated the within-subjects effect. However, for the simple one-way ANOVA, we only have one measurement per person so we use the avova1. My question is my data is structured for the repeated measures one-way ANOVA to see if there is any effect for both within-subject and between-subjects. For the between-subjects should I average the 10 measurements that were acquired from each person?

**Comment by 0todd0000** [comment]
Short answer:  for one-way ANOVA it is easiest to use **only** within-subject and within-condition means, and not individual measurements. For between-subject analysis, it is necessary to calculate within-subject means; otherwise, ANOVA interprets the multiple measurements as multiple subjects.

<br>

Consider the following interpretations of "multiple measurements" for one subject:
* (*c*) number of conditions
* (*m*) number measurements made for each subject for each condition

From your description it sounds like *c*>2, and *m*=10.

<br>

Here are a few related considerations:
* "Repeated measures" (RM) is unrelated to *m*. RM refers to the fact that *c*>1 and that *c* values are available for each subject, one for each condition.
* For basic RM-ANOVA it is possible to use *m*>1, but this procedure calculates within-subject means anyway, so that only *c* values are considered in analysis. Thus *m*>1 affects only within-subject, within-condition mean estimates.
* In Biomechanics, within-subject variability is usually much smaller than between-subject variability. This implies that *m*=1 and *m*=10 and *m*=100 will all produce effectively identical results in multi-subject experiments with RM designs.
* In one-way RM-ANOVA, only within-subject effects are of interest. That is, within-subject **change** across the *c* conditions is the dependent variable of interest. One-way RM ANOVA does not consider between-subject effects.

**Comment by meteor77** [comment]
Thank you Todd
