### ISSUE TITLE
reporting correlation coefficients

### ISSUE THREAD

**Issue by LWyers** [0todd0000/spm1d#147]
Dear Todd

Can I please ask your help to provide an answer to a reviewer? 

I performed SPM regression analyses and reported the correlation coefficients, since my target audience are clinicians that are not familiar with SPM and are used to interpret correlations. I plotted the curve of r over time and illustrated one specific time point using a scatterplot with the corresponding correlation coefficient.

The reviewer (who seems familiar with SPM) asked: 
"... are these correlation coefficients extracted from that specific time frame in the same 1-d SPM analysis, so basically just a snapshot of the graph on the left, or is it a different single time point (0-d) analysis? This could also be done in SPM I believe, or in any other software. The results could be different though when ignoring the temporal dependency.
Maybe very briefly specify that all these coefficients are the output of the SPM analysis of the 1-dimensional time series."

This question confused me. I did retrieve the coefficient from the spm output, but to my understanding, this should not differ from 0D analyses in other software. I thought the temporal dependency is only taken into account in the statistical inference and thus p-values. Could you please clarify this for me? Would it be better to add the specification as asked by the reviewer? Was I right and can I explain it like this?

Thanks a lot!

Lore

**Comment by 0todd0000** [comment]
Hello, you are correct, the correlation coefficient is the same regardless of software. Only the related probability values are different. In the scatterplot, if you included a p value in addition to the r value then I'd recommend removing the p value. Otherwise I think there's no problem. Perhaps you could respond by saying:

"The t statistic and corresponding correlation coefficient (r) were calculated at each time point. An example calculation at a single time point is depicted in the scatterplot. The t value and r values are unaffected by the inference procedure (0D vs. 1D)."
