### ISSUE TITLE
SPM1D regression normality test

### ISSUE THREAD

**Issue by Little-Foot-Shapes** [0todd0000/spm1d#153]
Hello Dr. Pataky, 

I am trying to do a normality test for a regression. My data is: 
variable one:   DATA_CU: 148x28382 (curvedness values for 148 foot point clouds consisting of 28382 points)
variable two:   Linear_Measure: 1x148 using this code (linear measure (normalized mid-foot width) of the same 148 feet)

The code I use is from the example: 

alpha     = 0.05;
spm       = spm1d.stats.normality.regress(DATA_CU, Linear_Measure');
spmi      = spm.inference(0.05);

When the inference is run the below error code comes up: 

Error using  ~ 
Operands must be real.

Error in spm_P_RF (line 94)
if     ~k || ~D

Error in spm_P (line 51)
[P,p,Em,En,EN] = spm_P_RF(c,k,Z,df,STAT,R,n);

Error in spm1d.rft1d.RFTProbability/cluster (line 15)
           p = spm_P(1, k, u, c.df, c.STAT, c.resels, c.n, c.Q);

Error in spm1d.rft1d.chi2.p_cluster_resels (line 50)
            p = calc.p.cluster(k, u);

Error in spm1d.geom.Cluster/inference (line 55)
                    p = spm1d.rft1d.chi2.p_cluster_resels(k, u, df(2), resels, 'withBonf',withBonf,
                    'nNodes',nNodes);

Error in spm1d.stats.spm.SPM/cluster_inference (line 124)
                    clusters{i} = clusters{i}.inference(self.STAT, self.df, self.fwhm, self.resels,
                    two_tailed, withBonf, self.nNodes);

Error in spm1d.stats.spm.SPM/inference (line 92)
            [clusters,p] = self.cluster_inference(clusters, two_tailed, withBonf);

Can you please help?

Thank you.

Best Regards
Mat

**Comment by 0todd0000** [comment]
Hello Mat,

Thank you for reporting this bug, I've not seen this error before.

Are there any zeros or `nan` values in `DATA_CU` or in `Linear_Measure`?

Can you please print and copy the value of `spm`?  (using `disp( spm )` )

Can you please plot and attach the `spm` result?  (using `plot( spm )` )

As an aside, please note that normality tests in **spm1d** are only suitable for 1D data. I am inferring from your description that each of the point clouds is a set of 2D or 3D coordinates. **spm1d** indirectly supports analysis of this type of data, but only its nonparametric procedures (in **spm1d.stats.nonparam**) are suitable for this purpose.  This doesn't explain the error, but for your future reference, please only use nonparametric procedures for this type of data.

Todd

**Comment by Little-Foot-Shapes** [comment]
Hi Todd, 

Thank you for your quick reply.

_Are there any zeros or nan values in DATA_CU or in Linear_Measure?_

No, there are not, however most of the values in DATA_CU are very close to zero. However, I get the same error when using shape-index data which ranges from -1 to +1. Using the same data I could complete the normality tests for ANOVA and independent t tests between groups (e.g. group 1: rows 1:12, group 2: rows 13-50).

_Can you please print and copy the value of spm? (using disp( spm ) )_

SPM{X2}
         z: [1×28382 double]
        df: [1 2]
      fwhm: 1.2764
    resels: [1 2.2235e+04]

_Can you please plot and attach the spm result? (using plot( spm ) )_

![DATA_CU_Linear_Measure_Regression_Normality_SPM_results](https://user-images.githubusercontent.com/49155177/100051237-431a8580-2e13-11eb-801b-a69fd5efbac8.jpg)

_As an aside, please note that normality tests in spm1d are only suitable for 1D data. I am inferring from your description that each of the point clouds is a set of 2D or 3D coordinates. spm1d indirectly supports analysis of this type of data, but only its nonparametric procedures (in spm1d.stats.nonparam) are suitable for this purpose. This doesn't explain the error, but for your future reference, please only use nonparametric procedures for this type of data._

Yes, I remember we discussed this before, and I use the non-parametric procedures. I am writing my thesis and I have to make sure I justify all my statistics. What would be the justification for using the non-parametric procedures? Would I still have to report the results of the normality tests?

Thank you for your help.

Best Regards
Mat

**Comment by 0todd0000** [comment]
> What would be the justification for using the non-parametric procedures?

A practical justification is: (1) **spm1d** only supports nonparametric procedures for 2D data, there are no software applications dedicated to 2D SPM analysis, and (3) 3D SPM packages support 2D analysis, but it usually requires a bit of hacking to get analysis to work.

A theoretical justification is: nonparametric procedures are suitable for all distributions.

> Would I still have to report the results of the normality tests?

No, nonparametric procedures are suitable for all distributions.


Regarding the plot:
There appears to be a serious bug, the data should not look like this.
Can you please try `plot(spm.z)` ?

**Comment by Little-Foot-Shapes** [comment]
Hi Todd,

Thank you. 

plot( spm.z) gives the same results. 

On a different note, have you got any developments re SPM1D power calculations in Matlab? I know you got it in Python...Also is there a way to calculate effect sizes for SPM tests?

Thank you for your help.

Best Regards

Mat

**Comment by 0todd0000** [comment]
> plot( spm.z) gives the same results

This can't be possible... something is strange. Have you set the axes to a log scale?

Please plot just Linear_Measure using `plot(Linear_Measure)` and attach the figure.
Please also plot `DATA_CU` using `pcolor(DATA_CU)` and attach the figure.

> On a different note, have you got any developments re SPM1D power calculations in Matlab? 

No, there are currently no plans to develop a power package for Matlab. 

> Also is there a way to calculate effect sizes for SPM tests?

Yes. **spm1d** does not have functions for calculating effect sizes, but they can be calculated in the usual manner, for example: mean  / standard deviation. One reason that **spm1d** does not support effect sizes is that they can be misleading when common, 0D data interpretations are applied to 1D data. In other words, it is highly likely that 1D random processes will produce effect sizes that would be interpreted as "medium" or "large" when using a 0D interpretation.

> Also, in your cross sectional foot pressure study you mention the t threshold of 2 and reference another one of your papers. I have failed to understand that paper. Is there a very simple way to explain how you arrived to that threshold?

That was an arbitrary threshold, with an alpha value much larger than 0.05.  For normal hypothesis testing, the threshold should be calculated based on an *a priori* alpha value.

> As it seems that (when I compare the 5 age groups using ANOVA and post hoc t tests) because I am doing multiple comparisons (10), after Bonferroni corrections the p becomes so low, that there are barely any significant differences. When I do regression width age, it is a little better, but still very low number of significant clusters\points.

This partially reflects reduced power due to to multiple tests. I would regard the main ANOVA result as the scientifically important result, and *post hoc* results as qualifying descriptions of that main result. From this perspective, you can do whatever you like in *post hoc* analysis, provided the results do not disagree with the main ANOVA results.


<br>
<br>

**Request**:  Please start new forum issues for new topics (e.g., power, post hoc analysis, etc.). We are trying to keep each forum issue as-focussed as possible. Thank you!

<br>
<br>

**Comment by Little-Foot-Shapes** [comment]
Hi Todd, 

_This can't be possible... something is strange. Have you set the axes to a log scale?_

I haven't.

_Please plot just Linear_Measure using plot(Linear_Measure) and attach the figure.
Please also plot DATA_CU using pcolor(DATA_CU) and attach the figure._

I have also plotted the data for the first foot (the first row of DATA_CU).

![plot_DATA_CU1](https://user-images.githubusercontent.com/49155177/100231906-8cf09200-2f1f-11eb-8dbe-5ec69c882b1f.jpg)
![pcolor_Data_CU](https://user-images.githubusercontent.com/49155177/100231912-8d892880-2f1f-11eb-8fbf-cda1a93eb0e4.jpg)
![plot_Linear_Measure](https://user-images.githubusercontent.com/49155177/100231914-8d892880-2f1f-11eb-8d78-ff933c0965c7.jpg)


Thank you for these and I am sorry, next time I will post those in a different forum.


Thank you.

Best Regards

Mat

**Comment by 0todd0000** [comment]
The `Linear_Measure` plot and the first row of `DATA_CU` both look fine, I don't see anything strange.
The pcolor plot looks odd, but I think it might be because the cell edges are hiding the cell colors...  please try re-plotting using:

```matlab
h = pcolor(z);
set(h,'facecolor','flat','edgecolor','none')
```

In both `DATA_CU` plots (both the first row of data and the `pcolor` plot) : the x axis goes from zero to `3 x 10^4`, as expected. This is would I would expect for `plot(spm.z)` as well.  I have no idea what is causing this problem.

Just to rule out any code issues, can you please paste the whole script into this thread, up to and including the following commands?

```matlab
alpha = 0.05;
spm = spm1d.stats.normality.regress(DATA_CU, Linear_Measure');
spmi = spm.inference(0.05);
```


I don't suppose any Matlab users are following this thread? Has anyone seen a problem like this before?

**Comment by Little-Foot-Shapes** [comment]
See the attached new pcolor plot, and I plotted the spm.z again.
![pcolorDATA_CUNEW](https://user-images.githubusercontent.com/49155177/100393301-193eaa00-3031-11eb-8fcd-e40ed7430789.jpg)
![plotspmzNEW](https://user-images.githubusercontent.com/49155177/100393305-1a6fd700-3031-11eb-9bd1-efe103d2a00a.jpg)



I dont really have any other code that would relate to this....I have the data in the workspace loaded, then I opened up your example script: ex1d_regression.m, changed the variables and ran it.

**Comment by 0todd0000** [comment]
The `pcolor` plot suggests that the data are not cleaned. If the data were clean, you would see all colors in Matlab's colormap, from blue to red. Since we can't see any red, it means that there are a few values, somewhere in the dataset, that are extreme outliers.

Regarding the `spm.z` plot:
My knowledge of Matlab plotting is limited, but from my understanding, this result is not possible if:

```
SPM{X2}
z: [1×28382 double]
```

If the above is true, then there must be just a single line that starts at x=1 and ends at x=28,382.

However, in the new screenshot you sent it is clear that the data are actually complex:

```
SPM{X2}
z: [1×35756 complex double]
```

When the data are complex, a result like the `spm.z` plot above is indeed possible. The complex result reiterates the `pcolor` point above:  the data are not cleaned properly, and this is causing numerical problems for regression.

I suggest the following:

* Go through each row of DATA_CU, separately plotting each row.
* You will likely find some very large numbers for one or more rows;  from the normality plot I suspect that the problem data will occur at around element 2000 (where the large spikes are in the normality X2 values).
* Get rid of the very large numbers somehow. A simple option is applying a threshold (i.e., forcing all values to be compressed to a certain maximum value). Another option is applying a spatial filter to the original 2D data.
* Continue cleaning the data until the `pcolor` plot shows a more even distribution of colors, from blue through dark red.
* Then re-run SPM;  the results will likely be non-complex, and will likely appear

<br>
<br>

**Please note**:

* 2D data cleaning is beyond the scope of the **spm1d** forums. If you need help with 2D data cleaning, please consider posting questions to another forum, for example: [stackoverflow](https://stackoverflow.com/questions/tagged/image-processing)

**Comment by Little-Foot-Shapes** [comment]
Thank you!
