### ISSUE TITLE
Format of Variables in 2 way ANOVA

### ISSUE THREAD

**Issue by Shivangi2208** [0todd0000/spm1d#157]
Hello Todd,
Thank you for helping me with my previous query. Now I need your help in understanding the format of variables used to perform a 2 way ANOVA test. I will briefly explain what I am trying to achieve. I have 10 subjects and 2 factors (model type and muscle configuration) for which I want to run this test to analyze the effects of both factors on the muscle force profile of these 10 subjects.
How can I format my data to achieve this. I tried taking the idea from the example ex1d_anova2.m but I keep getting errors regarding the format of my dataset. Attached below is the snippet of my code for your reference. I believe it is the group labelling array which I am describing incorrectly. Kindly help.

force= '*compare_muscle_forces.xlsx';

BFLH_1dof = xlsread(force,1);
P = BFLH_1dof(2:end,1:end);
BFLH_2dof_SM = xlsread(force,2);
Q = BFLH_2dof_SM(2:end,1:end);
BFLH_2dof_MM = xlsread(force,3);
R = BFLH_2dof_MM(2:end,1:end);

n0 = size(P, 1);  
n1 = size(Q, 1);  
n2 = size(R, 1);  

**I guess the problem exists here**
For model type (they are 3 types)
a0 = 0 * ones(n0, 1);  %group 0 labels
a1 = 1 * ones(n1, 1);  %group 1 labels
a2 = 2 * ones(n2, 1);  %group 2 labels

And 2 types of muscle configuration
b0 = 0 * ones(n0, 1);  %group 0 labels
b1 = 1 * ones(n1, 1);  %group 1 labels

M  = [P;Q;R];  %all data
A  = [a0; a1; a2];  %all group labels
B  = [b0; b1; b2];

spm = spm1d.stats.anova2(M,A,B);
ti = spm.inference(0.05);
disp(ti)

Regards,
Shivangi

**Comment by 0todd0000** [comment]
Hi Shivangi,

The problem is that the design matrix is not [full rank](https://en.wikipedia.org/wiki/Rank_(linear_algebra)), or in other words the A and B factors are linearly dependent, and actually in this case equivalent.  (`b2` is not defined above; I'm assuming it is `b2 = 2 * ones(n2, 1);` )

Let's consider a simpler example, with three A levels and two B levels. In this case A and B would need to be specified something like this:

```matlab
A = [0 0 0 0 0 0   1 1 1 1 1 1    2 2 2 2 2 2]';
B = [0 0 0 1 1 1   0 0 0 1 1 1    0 0 0 1 1 1]';
```

Unrelated to the errors, but a potentially important design consideration:
If each of the 10 subjects were involved in more than one level of A and/or more than one level of B, a repeated measures design would be more appropriate (e.g. **spm1d.stats.anova2rm**).

Todd

**Comment by Shivangi2208** [comment]
Thank you once again Todd for your help.

Regards,
Shivangi
