### ISSUE TITLE
2D pressure analysis: effect size to determine the minimum number of pressure records 

### ISSUE THREAD

**Issue by eleonora-mont** [0todd0000/spm1d#161]
Hi Todd,

I am working with plantar pressure data and I want to establish the minimum number of pressure records per subject required to achieve a stable mean representative of my sample gait. Would I be able to use effect size for this purpose? I have seen a conference paper where kinematics data was used for this purpose (attached) and the time series variance was statistically compared between groups of different N trials. However, I was wondering if reporting the effect size for each of the group could be a possibility too. The only "problem" I think I have is that the SD of pressure data I am working with is quiete high and this would affect the effect size. 

Thanks in advance for your help!
Eleonora 
[RECOMMENDATIONS FOR MINIMUM TRIAL NUMBERS DURING WALKING GAIT.pdf](https://github.com/0todd0000/spm1d/files/5994893/RECOMMENDATIONS.FOR.MINIMUM.TRIAL.NUMBERS.DURING.WALKING.GAIT.pdf)

**Comment by 0todd0000** [comment]
Hi Eleonora,

I must disclose that I am a co-author on a paper that is directly related to your question, and that is currently under review, so at this moment I am unfortunately unable to provide advice regarding how achieving a stable mean could or should be done.

I am happy to discuss **spm1d** analysis possibilities and how specific calculations can be performed, so please feel free to ask any specific calculation questions like these. Perhaps relevant to your question is [power1d](https://spm1d.org/power1d/Examples.html), which is housed within **spm1d** but not directly integrated, and which supports numeric sample size calculations.

Todd

**Comment by eleonora-mont** [comment]
Hi Todd,

Thanks for you reply. I had a look at sample size calculation provided by power1d and see that it could possibly fit in my initial question. However, I struggle to understand how to apply sample size calculation to pressure data. I have seen it used mostly in kinematics so I appreciate if you could clarify to me this:

1. in the first three lines of code:
J          = 5    # sample size
Q          = 101  # continuum size
q          = 65   # signal location

What continuum size and signal location would be for plantar pressure data? 

Thanks again
Eleonora

**Comment by 0todd0000** [comment]
Continuum size is easier: `Q` it is the number of continuum nodes, so for pressure data it would be the number of sensors or number of pixels.

The signal location is tougher:  in the **power1d** example, `q` is the position over which the modeled signal is centered, and the signal is modeled as a Gaussian pulse. If the data domain is actually 2D, you would need to model both the noise and the signal in a different way. Here is an approximate procedure:

1. Model 2D noise over the domain of interest (i.e., smooth 2D noise with a similar smoothness and amplitude to experimentally observed 2D noise, and acting over average 2D foot geometry).
1. Model a 2D signal. For example:  a 2D Gaussian pulse centered over a specific 2D location.
1. Conduct numerical power analysis, for example using the procedures in **power1d**.  Roughly: simulate many datasets that represent your experimental design (e.g. for sample size N, generate one group with signal, one group without signal), calculate power, then repeat, changing `N` until the desired power is reached.

**power1d** supports only (3). (1) and (2) would have to be custom-written. (2) is relatively easy, and can be done for example using a [2D Gaussian pulse](https://gist.github.com/andrewgiessel/4635563).  (1) is more difficult. You would separately need to generate: (1a) a 2D random noise generator, and (1b) representative foot geometry. (1a) could be done, for example using a modification of [this Matlab script](https://www.fil.ion.ucl.ac.uk/~wpenny/mbi/randomtalk.m), which comes from a [2006 Mathematics for Brain Imaging course](https://www.fil.ion.ucl.ac.uk/~wpenny/mbi/).  (1b) could be done most easily using public average morphology data, like the [mun104 dataset](https://github.com/0todd0000/mun104), but these data are not necessarily representative of the target population's morphology in your study.

All of the information above is published or otherwise public, but this discussion is starting to get close to non-public details in a currently in-review paper, so please understand that I'm unable to share more details until after the paper's review process is complete.

**Comment by eleonora-mont** [comment]
I appreciate this! Thanks!

Eleonora
