### ISSUE TITLE
Curious result, data problem ?  & question about post-hoc test 

### ISSUE THREAD

**Issue by Thomas76000** [0todd0000/spm1d#168]
Hello, 

I performed an anova on my dataset comprising 3 groups (n = 4 for each). The data correspond to the variation of the jerk of the foot during the walk (inversion - eversion) 

Here is a result I got for my anova (ex1d_anova1.m). 
![anova](https://user-images.githubusercontent.com/83072739/116113574-e3bdeb80-a6b8-11eb-9576-06ac89ba17b8.png)

The graph seems a bit inconsistent with other results I've had. I wonder if this is normal, or if it could be the Consequence of errors in the acquisition of data within my different groups. 

Moreover, when I perform post-hoc tests (anova1_posthoc) and a paired t-test (ttest_paired) I find significant results with the paired-ttest but not the post-hoc anova, is this normal? 
Which test should I turn to in this case?  

ANOVA_POSTHOC
![anova_posthoc](https://user-images.githubusercontent.com/83072739/116115116-59768700-a6ba-11eb-95fb-c84f393730c8.png)
PAIRED-TTEST
![paired-ttest](https://user-images.githubusercontent.com/83072739/116115160-65fadf80-a6ba-11eb-8b40-7a4c0aa49ab2.png)

ICC DATA 
![ICC_data](https://user-images.githubusercontent.com/83072739/116115198-70b57480-a6ba-11eb-9cb4-7e6b0336f2fd.png)

PP DATA 
![PP_data](https://user-images.githubusercontent.com/83072739/116115222-7743ec00-a6ba-11eb-934c-b0e8ac47d941.png)

PC DATA 
![PC_data](https://user-images.githubusercontent.com/83072739/116115479-ba05c400-a6ba-11eb-9545-8f9a9eb8fd69.png)

I hope this is understandable, thank you for your reply

**Comment by 0todd0000** [comment]
I'm not certain if this will solve the problem, but here are some considerations:

- If the original test is a between-subjects ANOVA (e.g. `spm1d.stats.anova1`), then you should only use between-subjects *post hoc* tests (i.e., `spm1d.stats.ttest2`)
- If the original test is a within-subjects ANOVA (`spm1d.stats.anova1rm`), then you should only use within-subjects *post hoc* tests (i.e., `spm1d.stats.ttest_paired`)
- Two-sample and paired tests will generally yield different results because the former is between-subjects analysis (i.e., comparing groups) and the latter is within-subjects (i.e., comparing individuals' changes across groups)

<br>
<br>

**Please note**: `anova1_posthoc` is not an **spm1d** function. If this is a custom function it can not be supported in this forum.

**Comment by Thomas76000** [comment]
Thank you very much for your answer, it is already clearer for me now, I will try this .
