### ISSUE TITLE
Mixed ANOVA vs SPM

### ISSUE THREAD

**Issue by berman954** [0todd0000/spm1d#171]
Hello Dr. Pataky,
* I have two groups and two conditions. Actually, I created two condition as non-fatigue and fatigue. Because I want to see that how fatigue effects these groups.
* I used 2 groups x 2 conditions (2-way mixed ANOVA). But subjects actually performed one session and I analysed first and last repetitions (total, 2). I used one-camera from sagittal plane for kinematics (2-D). Actually, it can be evaluated as a 1-D variable output. After I got my outputs from motion analysis software, I created different regions for applying specific evaluation, after that I guess SPM coming up in this regard.
*Different regions for same movement cycle. But I don’t compare variables between regions such as knee linear acceleration and deceleration. I divided as a different region and I compare variables between fatigue and non-fatigue conditions. Same region for before- after fatigue (knee acceleration in non-fatigue and knee acceleration in fatigue). So, I think that I don’t need to use SPM, Am I right?

*If I don’t perform SPM analysis, can ICC be logical? I found some bad results, so can it be proof for SPM? Or is SPM still compulsory for my analysis?
*If it is compulsory, which analysis should I apply with SPM? Paired-test for before-after conditions? or/and reorganise data for groups and use independent t-test or ANOVA with SPM? my mind confused a bit for this issue.

I would appreciate it if you could help. 
Thank you.

**Comment by 0todd0000** [comment]
> So, I think that I don’t need to use SPM, Am I right?

The appropriateness of a technique depends mainly on the experiment's *a priori* null hypothesis. If no specific variables were of interest before the experiment started, and you were instead interested in general kinematics (i.e., all measured data), then SPM or a similar technique may be appropriate because these techniques operate at the whole-dataset level.  Alternatively, if you had a specific, justifiable null hypothesis regarding the specific regions you mention, then SPM or a related whole-dataset technique is probably inappropriate.

> If I don’t perform SPM analysis, can ICC be logical? 

If you calculate ICCs, they should be calculated on the same data / variables that you report. Note that ICCs can be calculated for curve data (Pini et al., 2019).

Pini A, Markström JL, Schelin L. Test–retest reliability measures for curve data: An overview with recommendations and supplementary code. Sports biomechanics. 2019 Oct 4:1-22.

> which analysis should I apply with SPM? Paired-test for before-after conditions? or/and reorganise data for groups and use independent t-test or ANOVA with SPM? my mind confused a bit for this issue.

In **spm1d** the appropriate procedure might be `spm1d.stats.anova2onerm` (two-way ANOVA with one repeated-measures factor).

**Comment by berman954** [comment]
Thank you very much for your reply, I got it. I will try as soon as possible.
