### ISSUE TITLE
SPM Cluster Sizes

### ISSUE THREAD

**Issue by Variabrookity** [0todd0000/spm1d#175]
Hi,

I am a PhD student that is using SPM analysis to quantify significantly different coordination variability throughout the gait cycle under different loads. I am currently in the process of running this data and have noticed the varying widths in cluster sizes for the significant differences (e.g. a significant difference was found between 0% and 1.9% of the gait cycle as well as between 66% and 100% of the gait cycle).

I am still learning about the underlying theory of SPM however I just want to gauge if others have set a minimum cluster size that they report. For example, only presenting clusters that are 5% or greater of the gait cycle. 

Thanks

**Comment by 0todd0000** [comment]
This is a very good, and also very complex question!
There are two issues to consider: (1) reporting, and (2) theory relevant to minimum cluster sizes.

<br>

The easy part first (reporting)...

As far as I know, there are no specific standards for describing SPM results, in terms of reporting or not reporting small clusters. If you present the data graphically (including the clusters), then I think you needn't also mention all specific cluster information in the text.  If, on the other hand, you only report the results in text or in tables, then I think it would be most objective to report all clusters. If there are a large number of small clusters I'd suggest reporting these as supplementary material, as they are likely not relevant to overall results interpretations.

<br>

The tougher part (theory)...

SPM theory permits minimum cluster size thresholding. In addition to the typical false positive threshold of alpha=0.05, one can easily include a minimum cluster size threshold (e.g. 1%, 5%, etc.). The mathematics behind this are relatively straightforward, and this is already implemented in **spm1d**, albeit not easily accessible.

However, whether it is justifiable to use a minimum cluster threshold is another matter altogether. The Neuroimaging literature often uses minimum cluster thresholds, but this thresholding is justifiable based on extensive research regarding the spatiotemporal characteristics of blood perfusion and oxygenation. It is highly likely that a single, isolated voxel which reaches significance, is caused by noise and not real physiological signal.

In Biomechanics the spatial / temporal characteristics of biomechanical changes have also been well studies, but the expected spatiotemporal characteristics of biomechanical changes can vary dramatically between tasks (e.g. slow vs. fast), populations (e.g. young vs. elderly), and also due to many other factors. I therefore think it would be difficult to justify a specific cluster threshold unless the spatiotemporal nature of the hypothesized signal were well justified.

In Biomechanics there is an additional problem: all data processing steps can affect the spatiotemporal nature of expected signals. This is most obvious for filtering / smoothing, where smoother data is expected to yield larger clusters. However, other processing steps like segmentation (e.g. gait cycle extraction) and registration (e.g. temporal normalization) can also affect the nature of signals.

<br>

So overall I'd suggest:
- Report all clusters, either implicitly in figures, or explicitly in text / tables
- Optionally use supplementary material if these details are irrelevant to the overall conclusions 
- Do not use a cluster size threshold unless very clearly justifiable based on biomechanical and data processing rationale
