### ISSUE TITLE
Appropriate RM analysis for unequal group sizes

### ISSUE THREAD

**Issue by RiadAkhundov** [0todd0000/spm1d#182]
Hi Todd,

Since unbalanced designs are not yet supported for ANOVA/MANOVA in spm1d, I am struggling to find an appropriate SPM analysis for my study:  

Kinematics were measured for two groups (19 control and 6 pathological) in five different conditions (ten repetitions for each condition). Additionally, the approach speed was recorded (single value per repetition).

Which SPM analysis can I use to investigate the effects of the groups, the conditions, the approach speed (maybe as a continuous predictor) and their interactions?

Kind regards,
Riad

**Comment by 0todd0000** [comment]
One way to analyze these data using the current version of **spm1d** is to impose design balance by (1) randomly selecting a subset of subjects, (2) analyzing, then (3) repeating 1 and 2 for a number of random subsets. In this case you would probably use two-way repeated measures (RM) ANOVA with one RM factor (**spm1d.stats.anova2onerm**).

However, complicating matters is the extra continuous factor (approach speed), which should ideally be included in a model, and which would make it an ANCOVA model. However, general ANCOVA is not supported in the current version of **spm1d**.

Another option for analyzing data like these --- when there is a Control group --- is to use the Control mean as a datum, and to conduct a one-way analysis. However, even in this case you would need to use an ANCOVA model if you want to include approach speed.

A potential additional complication is the nature of the dependent variable (DV). If "kinematics" means multiple variables (e.g. multiple joints, multiple angles for each joint, etc.), and thus that the DV is multivariate, then MANCOVA would likely be best. MANCOVA is also unsupported.

To summarize: the most appropriate design in this case sounds like: two-way repeated-measures MANCOVA with one RM factor. Unfortunately **spm1d** is currently unable to support a design as complex as this. Since the design is complex, it is not obvious how it could or should be decomposed into simpler analyses.

I'd suggest starting with a simple, univariate 0D DV like maximum angle, and implementing ANCOVA in separate software like SPSS or R. If you can get it working there, you will be able to explore a variety of options for decomposing the ANCOVA into sets of simpler analyses, including sets which impose balance through random subject selection. If you can get everything working acceptably for this simple, univariate DV, then try again for multiple DVs and MANCOVA. If that works, then it would probably be acceptable to apply the same strategy to 1D DVs using **spm1d**.

**Comment by RiadAkhundov** [comment]
Thank you very much Todd!

Appreciate your quick feedback.
Cheers
