### ISSUE TITLE
Choice of multivariate vs repeated measures

### ISSUE THREAD

**Issue by bernard-liew** [0todd0000/spm1d#20]
Dear Todd,

Sorry I have been opening up to many issues, but I am actively using SPM for myself and other studies too, so they have been posing interesting questions. The issue is not SPM per se, but may be more pertinent with spm1d. The data I have that we are interested in has 6 dependent variables: 1) hip angle (xyz) and knee angle (xyz). This was a single group repeated measures on two factors: 1) speed (3,6) and 2) tape (1,2,3). 

The choice I am deciding between is 1) do 2wayRM anova on each of 6 dependent variables, or 2) do a hotelling paired t test on each hip and knee vector, for each pair wise factor comparison. 

What should my decision be based on? My initial thinking was to choose the one that will require least repeated stats testing. But I am interested in how tape influences the covariation of hip angles in three planes. Any advice??

Regards,
Bernard

**Comment by 0todd0000** [comment]
Dear Bernard,

This is a good question, but difficult to answer because it pertains to general statistics and not specifically to the **spm1d** software.  Please understand that, while we support the software for free, we cannot also support general statistics questions.

However, in this case here is a good rule-of-thumb:
If your dependent variable is multivariate (which it clearly is in this case) then you must use multivariate methods because the individual variables are generally non-independent. The appropriate model is likely a two-way RM MANOVA or MANCOVA, but neither is currently supported in **spm1d**.

Todd
