### ISSUE TITLE
Queries on SPM

### ISSUE THREAD

**Issue by learnlive2** [0todd0000/spm1d#218]
Hello, 

May I enquire about the following for SPM:
1. Scaling: When we carry out the spm1D analysis, we have a different criteria t statistic for each component in a joint. May I ask if we can calculate the effect sizes or each joint? Alternatively, is there a scaling method so that we can understand the relative effects of one component or joint with respect to the other?
2. Assumptions: Do we require and should we test that our data meet the assumptions of using the parametric statistical analyses and random field theory before we run the SPM1D analyses?

Thank you so much.

**Comment by 0todd0000** [comment]
> May I ask if we can calculate the effect sizes or each joint?

Yes, effect sizes can be calculated in the usual way. However, **spm1d** does not support effect size calculations because common effect size interpretations like "Medium" and "Large" do not apply to 1D data. For an 1D data one is far more likely to observe "Medium" and "Large" effects (for example) when the true effect is zero than for 0D data.

<br>

> Alternatively, is there a scaling method so that we can understand the relative effects of one component or joint with respect to the other?

I am not sure what "scaling" means, can you please clarify?

<br>

> Do we require and should we test that our data meet the assumptions of using the parametric statistical analyses and random field theory before we run the SPM1D analyses?

Normality tests can indeed be conducted, but a better general approach is to conduct both parametric and nonparametric tests. If the results agree then the parametric approach's assumption of normality is inconsequential and likely reasonable. If the results disagree then additional analyses (like normality tests or outlier removal) should be conducted to explain the disagreement.

**Comment by learnlive2** [comment]
Hi Dr Pataky,

Thank you very much for your reply.
For the "scaling", could there be a "scaling" using a reference?

Thank you once again.

**Comment by 0todd0000** [comment]
I'm still not sure what you mean by "scaling". Can you please send a link to a paper or site that describes what "scaling" is?

**Comment by learnlive2** [comment]
Thank you so much Dr Pataky. I found quite a few discussions on effect size in this forum. I will read them and see if I could incorporate the effect size instead. Thank you once again.
