### ISSUE TITLE
Post-hoc for vector field paired Hottelling's T

### ISSUE THREAD

**Issue by bernard-liew** [0todd0000/spm1d#22]
Hello Todd,

I have a question on the above, and I acknowledge that it might have been asked previously (see https://github.com/0todd0000/spm1d/issues/3). I do not however feel I understood the answer

I am doing multiple paired SPM T2 on a vector with three components in gait. The test demonstrate 2 significant clusters. I proceeded to do post hoc using paired t test. I detected significance in the scalar post-hoc in phases of gait where the vector did not show a significant cluster.

Can I ask the meaning of this and how one should interpret (of if it is wrong iin the first place)

Regards,
Bernard

**Comment by 0todd0000** [comment]
Hi Bernard,

If the clusters do not appear in the original Hotelling's T2 test, then the post hoc results are not valid. Proper post hoc procedures must not be run on arbitrary components, but instead on a linear combination of components. The following two discussions are relevant:

http://stats.stackexchange.com/questions/129123/how-can-manova-report-a-significant-difference-when-none-of-the-univariate-anova

http://stats.stackexchange.com/questions/111044/post-hoc-tests-for-manova-univariate-anovas-or-discriminant-analysis

A key point from the first discussion is that you cannot run post hoc tests on arbitrary vector components because the vector component are often correlated.
A key point from the second discussion is that multivariate analyses are conducted when you have no specific hypothesis regarding the vector components.

Todd

**Comment by bernard-liew** [comment]
Dear Todd,

thank you for the reply. In your paper "Vector field statistical analysis of kinematic and force trajectories", you mentioned the pitfall of post-hoc scalar field analysis after a vector field, as not accounting for co-variance between vector components.

In the field of spm, but maybe outside of spm1d's current version, what would be the least bias way of performing a post-hoc after vector field analysis, that takes into account co-variation?

regards,
Bernard

**Comment by 0todd0000** [comment]
Hi Bernard,

Just as there is no fundamental difference between 0D and 1D post hoc testing for ANOVA, there is also no fundamental difference between 0D and 1D post hoc testing for MANOVA and other multivariate techniques.  Thus all textbooks and literature which describe post hoc analyses for 0D tests are directly applicable to 1D analysis. Please study those techniques to help you choose the best procedure for your particular application.

Since post hoc tests are not yet implemented in **spm1d** please understand that we cannot support them further at this time.  Post hoc analyses may be available in the next major version of the software, currently planned for release in Summer 2016.

Cheers,
Todd
