### ISSUE TITLE
Display P-value for nonsignificant differences

### ISSUE THREAD

**Issue by menzejo** [0todd0000/spm1d#222]
Dear SPM experts

We would like to display the range of p-values for nonsignificant differences in a continuous comparison between two groups using the Mann Whitney U test. We were curious if there is an option to do this using SPM, in the graphs below for example in the range between 40° to 60° of shoulder abduction:
![Picture1](https://user-images.githubusercontent.com/64215489/179216511-742c04a1-167c-4eb1-a6b4-63bf1da51fac.png)

When we do see significant differences the P-value is automatically depicted as below:
![2022-07-15_13-42-37](https://user-images.githubusercontent.com/64215489/179217299-e7ef80c1-229b-45ee-9c25-8a27b54372e4.png)

I am looking forward to your response!

Thank you and best regards
Johanna Menze
(johanna.menze@unibe.ch)

**Comment by 0todd0000** [comment]
There are two problems with displaying p-values greater than alpha:

1. Cluster-level inference:  these p-values are specific to clusters, as in the results above. A cluster exists only when alpha-defined threshold is traversed, so there are no clusters --- by definition --- when alpha is not traversed. So "non-significant"  p-values do not exist for cluster-level inference.

2. Point-level inference: it is indeed possible to calculate p-values for individual points, but (a) these p-values become inaccurate why p gets large (p > 0.4), and (b) those p-values are not directly comparable to cluster-level results because they are different probabilities.

I therefore recommend against reporting p-values when p > alpha, and instead reporting just "p > alpha".  This follows standard SPM practice for reporting cluster-level probabilities. Will this be satisfactory?
