### ISSUE TITLE
what dose the "iteration" mean in SPM nonparametric analysis code

### ISSUE THREAD

**Issue by Xlcandy** [0todd0000/spm1d#233]
Hi, Todd

I would like to conduct some nonparametric analysis like nonparam hotelling paired t-test and nonparam paired t-test etc.
But I found that all the spm code there have a word "iterations", and if I change the number behind it, the result will also change. 
I would like to ask that, what dose the "iteration" mean? and what is the appropriate range of the number behind it for hotelling test and paired t-test?

<img width="427" alt="截屏2022-10-09 17 39 15" src="https://user-images.githubusercontent.com/104749353/194746861-a8d9844e-0220-489e-a550-745746625654.png">

Thank you all the time. 
:)

**Comment by 0todd0000** [comment]
An iteration is a random permutation of the observation's labels. Generally: it should be 10,000 or 100,000, or as big as possible in order to achieve stable results. 

Please find relevant discussions in issues #63, #116, and #187.

Here is a wonderful paper describing permutation-based inference:
Nichols, T. E., & Holmes, A. P. (2002). Nonparametric permutation tests for functional neuroimaging: a primer with examples. Human Brain Mapping, 15(1), 1-25.
https://onlinelibrary.wiley.com/doi/abs/10.1002/hbm.1058

Please feel free to continue the discussion here if any questions remain.

**Comment by Xlcandy** [comment]
Oh many thanks!
