### ISSUE TITLE
Interpretation of SPM 

### ISSUE THREAD

**Issue by ccmkine** [0todd0000/spm1d#243]
1) I have used SPM to assess in which part the signals differ. Nevertheless, other authors suggest that SPM should be interpreted as the signals differ in their waveform. **What is the correct way to interpret the p-value given by the SPM1d?**
2) If I found that two signals differ in a normalized gait cycle. For instance, between 10-11 % of the cycle.  **Is it correct to say that the signals are different?**
**Do you recommend some threshold to state that both signals differ?** For example, more than 3-5 % of the cycle.
3) **What is the main limitation of the SPM1d analysis?**

Thank you in advance 
Carlos

**Comment by 0todd0000** [comment]
1) **What is the correct way to interpret the p-value given by the SPM1d?**

Cluster-level p-values represent the probability that a random (Gaussian) 1D continua with the same smoothness as the observed residuals would produce a cluster of equivalent or greater breadth when the null hypothesis is true.

<br>
<br>

2) **Is it correct to say that the signals are different?**

The signals may indeed be different, but this is only one possibility, so a slightly more nuanced interpretation is required. Another possibility is that the true mean signals are exactly the same and that the observed apparent effect was caused by sample peculiarities. One can never use hypothesis testing to claim that two population means differ;  instead hypothesis testing results (when p < alpha) suggest only that the observed effect would occur relatively rarely (with a probability of p) in an infinite number of experiments when the null hypothesis is true. So while the two signals may indeed be truly different, hypothesis testing cannot tell you whether they are indeed truly different.

<br>
<br>

**Do you recommend some threshold to state that both signals differ?**

I cannot recommend a threshold because this is a scientific, technological and perhaps even application-specific question. A very noisy measurement system, for example, may create several very small clusters. In this case it may be advantageous to employ a cluster size threshold. However, justifying your choice of cluster size threshold would require a sound theoretical or numerical argument.

<br>
<br>

3)  **What is the main limitation of the SPM1d analysis?**

SPM shares many limitations with other techniques. For example, it has all of the weaknesses (and strengths) of general hypothesis testing including: (i) its value is limited by the scientific quality of the null hypothesis, (ii) its can be over- or under-powered, etc.  It also shares limitations with all techniques that consider multiple 1D (or nD) data measurements to be directly comparable, namely: it requires registration, but registration might not be ideal or even possible in some situations. It is also limited with respect to techniques from the functional data analysis (FDA) literature in that assumes a relatively simple model of randomness; nevertheless, this model simplicity is also one of SPM's greatest strengths: it permits rapid and rather accurate parametric calculations of 1D-relevant probabilities. So while SPM has many limitations I'm not sure that there is a limitation that is specific to SPM.
