### ISSUE TITLE
following up a 2 way ANOVA with  one factor repeated measures

### ISSUE THREAD

**Issue by adrianrivadulla** [0todd0000/spm1d#250]
Hi Todd,

I hope you’re well.

I am a bit confused as to how complete my SPM analysis and I was hoping you’d be willing to share some of your knowledge.

I’ve two groups that have been tested running at three different speeds. I want to understand whether these two groups changed their technique differently as speed increased. I used a 2-way ANOVA with one repeated measures factor (speed). There was an interaction effect between group (and speed and main effects of those factors too). Therefore, groups responded differently to speed as per the significant interaction effect found in certain phases of the gait cycle.

I am now wondering how to go about further testing or discussing the interaction effect. In 0D stats you’d look at the interaction graphs but can I do something similar with SPM? Like looking at the difference across the entire curve as speed increases for one group and the other and then discuss them qualitatively? Or post hoc tests? But I am a bit unsure about this since what would I do? 2 groups x 3 speeds means 15 comparisons but does it make sense to compare group A at speed 1 to group B at speed 3? On the other hand, I’ve also seen threads on stackexchange suggesting leaving it here since we’ve already seen that there’s an interaction effect which was our main question.

Have you got any thoughts on this?

 Thank you so much and I look forward to your answer.

**Comment by 0todd0000** [comment]
As far as I know there is no established, formal way to probe interactions for 1D data, and my general opinion is that all secondary analyses are fine provided the main ANOVA result is indeed regarded as the main result, and that secondary analyses are indeed regarded as secondary (i.e., secondary attempts to explain the main ANOVA result).

In the particular case of the design and results you describe,  I'd suggest (a) plotting the means, and (b) adding a vertical background bar or some other indicator of the interaction.  It may be possible to see in this region that within-group changes are different for the two groups.

As you suggest, *post hoc* paired t tests would also be a possibility. Just two comparisons may work:

- Comparison 1: change from Speed-1 to Speed-2  (one mean value for each group)
- Comparison 2: change from Speed-2 to Speed-3  (one mean value for each group)


<br>
<br>

> I’ve also seen threads on stackexchange suggesting leaving it here since we’ve already seen that there’s an interaction effect which was our main question.

Yes, I'd concur with this interpretation. ANOVA results are the main results because the employed ANOVA model is presumably that model that most closely represents the experiment in its entirety.  If one were truly interested in ONLY Speed-2 vs. Speed-3, for example, then the experiment would or should have been designed differently. So I believe that these StackExchange threads convey the same idea as the one above regarding main vs. secondary analyses.

**Comment by adrianrivadulla** [comment]
Great, thank you so much Todd. I think we can close it here unless you have anything else to add?
