### ISSUE TITLE
Extracting Cluster Data from 2 Way RM ANOVA

### ISSUE THREAD

**Issue by jlit29** [0todd0000/spm1d#268]
Hi Todd,

I wish to extract the specific X axis coordinates where my 2 way RM anova SPM analysis found statistical significance. I used the following code to print the inference output:
`
FF = spm1d.stats.anova2rm(Y, A, B, SUBJ)
`
`
FFi = [F.inference(alpha=0.05) for F in FF]
`
`
print(FFi)
`
When I try to run
`
print(FFi.clusters)
`
I get an error. When I run:
`
print(FFi.clusters for F in FF)
`
I get "generator object <genexpr> at ....". I tried to convert the object to a string, list, and tuple but this didn't work either. Please let me know how I can access the cluster outputs. Thank you for your time.

**Comment by 0todd0000** [comment]
As a quick answer, try:

```python
print( FFi[0].clusters )
```

or:

```python
for Fi in FFi:
    print( Fi.clusters )
```

<br>

Notes:
- Clusters are only calculated at the inference stage, so you must access clusters from the inference outputs (i.e., from `FFi` and not from `FF`)
- Since clusters are specific to a particular F curve, you need to first access a single F curve (e.g. `FFi[0]`), then you can access its clusters
