### ISSUE TITLE
Curves of data in regression analysis in SPM

### ISSUE THREAD

**Issue by Hart-J** [0todd0000/spm1d#276]
Hello, sir

I would like to inquire about the regression analysis involving EMG RMS and running economy in SPM. Should the subjects ideally exhibit a similar RMS curve? Because I have noticed that a couple of subjects have RMS curves that are not quite the same.

Thank you for your kind assistance. Looking forward to your reply.

**Comment by 0todd0000** [comment]
Similarity in SPM is judged based on the quality of registration, which is usually referred to as "temporal normalization" in biomechanics. Provided you have registered the data to a common time domain (usually 0-100% time) over which it is suitable to calculate mean and standard deviation curves, then it is also suitable to conduct SPM analyses.

**Comment by Hart-J** [comment]
Hi Todd,

thank you for your reply.
![屏幕截图 2024-02-03 193845](https://github.com/0todd0000/spm1d/assets/158445788/2e791e6e-0c91-40cd-b20b-8e728f87d509)

I would also like to further confirm that I have done time normalization and the curves for several subjects are roughly as follows, is it possible to do SPM analysis? Or do I need to eliminate the abnormal subjects before I can proceed to the next step of analysis.

Thank you for your support.

**Comment by 0todd0000** [comment]
It would seem that there are substantial temporal differences amongst these observations. In this case nonlinear registration may be necessary. [Here is a notebook](https://github.com/0todd0000/nlreg1d/blob/main/Notebooks/3-Registration.ipynb) demonstrating how this can be done using [nlreg1d](https://github.com/0todd0000/nlreg1d) which is just a high-level interface to [fdasrsf](https://github.com/jdtuck/fdasrsf_python)

**Comment by Hart-J** [comment]
Hi Todd
Thank you very much for your reply. I've read your advice carefully, but still have a couple of minor questions. 

Firstly, the data after the non-linear alignment does not seem to fit well, can it be used or should the data be culled. 

Secondly, if it can be used, should a statistical non-parametric mapping be used? How is it different from statistical parametric mapping?

 Lastly, in the research I have been doing, I have found that when performing correlation analyses of discrete values the results are significant, whereas SPM is not, what could be the reason for this?

There seem to be a lot of questions, so I hope you can answer them in your busy schedule.
 Thanks again and its looking forward to your reply.
![Uploading Figure_1.png…]()

**Comment by Hart-J** [comment]
Hi Todd
Thank you very much for your reply. I've read your advice carefully, but still have a couple of minor questions.

Firstly, the data after the non-linear alignment does not seem to fit well, can it be used or should the data be culled.
<img width="462" alt="屏幕截图 2024-02-06 114132" src="https://github.com/0todd0000/spm1d/assets/158445788/0324220d-01bc-44ac-8502-63de0115701f">

Secondly, if it can be used, should a statistical non-parametric mapping be used? How is it different from statistical parametric mapping?

Lastly, in the research I have been doing, I have found that when performing correlation analyses of discrete values the results are significant, whereas SPM is not, what could be the reason for this?

There seem to be a lot of questions, so I hope you can answer them in your busy schedule.
Thanks again and its looking forward to your reply.

**Comment by 0todd0000** [comment]
Nonparametric inference should generally be used if the data are not normally distributed. However, the issue of parametric vs. nonparametric inference is not directly related to registration. 

It appears that time is being excessively warped: the registration approach has simply pushed all local maxima to a common point. This may imply that the data are non-registerable;  there may be no time domain for which each domain point corresponds to a homologous event across all observations. Based on the results above it may be possible that homolgous events cannot be identified across all curves, in which case the data are not registerable and SPM analysis should not be conducted. Note that registration is a requirement of SPM and similar approaches.

<br>
<br>

> Lastly, in the research I have been doing, I have found that when performing correlation analyses of discrete values the results are significant, whereas SPM is not, what could be the reason for this?

SPM thresholds are higher than thresholds for discrete values because of the data volume. When the amount of data (e.g. the number of variables) increases, the threshold must rise in order to maintain Type I error rate at alpha (usually alpha=0.05).
