### ISSUE TITLE
Unexpected Repeated-Measures ANOVA Result

### ISSUE THREAD

**Issue by joshuatbland** [0todd0000/spm1d#284]
Hello. I have run a one-way repeated measures ANOVA on a dataset - I have included a plot of the ANOVA results and a plot for each subject. The ANOVA results suggest there are only significant within-subject differences between conditions at the very start of the trajectory. This doesn't seem to line up with what we are seeing in the individual subject plots. Any insight into this would be greatly appreciated.

![SPM_Question](https://github.com/0todd0000/spm1d/assets/137851275/3c446c09-7783-44d3-8f91-9e44b5bcf00a)

**Comment by 0todd0000** [comment]
Please try plotting pairwise differences instead of condition means themselves:

- Fig.1: `(Cond2 - Cond1)`  for all six subjects
- Fig.2: `(Cond3 - Cond1)`  for all six subjects
- Fig.3: `(Cond3 - Cond2)`  for all six subjects

RM-ANOVA considers only these pairwise difference so these plots will likely be more similar to the RM-ANOVA results.

Note that the between-subjects result (black line in top right panel) considers just the condition means so this result should be qualitatively similar to the condition means as plotted above. From the top left panel this seems to be correct: there seems to be more separation amongst the conditions in the second half of the trajectory, and this is reflected in slightly larger F-values.

**Comment by joshuatbland** [comment]
I have added the plot with the pairwise differences below:
![Pairwise_Difference_Plots](https://github.com/0todd0000/spm1d/assets/137851275/33776dbc-a098-4354-9881-0f48198e2ab5)

**Comment by 0todd0000** [comment]
Thank you for these additional figures. These results appear to agree with the RM-ANOVA results: the biggest deviations from zero occur at around 0-100, in both (cond2-cond1) and (cond3-cond1).
