### ISSUE TITLE
RFT analysis

### ISSUE THREAD

**Issue by bernard-liew** [0todd0000/spm1d#31]
Dear Todd,

I am wanting to ask some help on RFT analysis.

Study. I have 32 participants [17 normal and 15 hypermobile kids], doing a cut task at their self selected speed. We wanted to use RFT rather than a standard two sample T test or even a hotelling’s, as each subject speed was self selected. This means there is intertrial and inter subject variation. In addition to speed, although cut angle was prescribed at 45 deg, we found significant variation away from that. Hence, there is inter-trial and inter-subject variation in angle.

My RFT analysis on knee X moment did not produce significance at a level two analysis. But when I used a normal 2 way t test, there was.

I tried both random effect of speed (ie x= SPEED) and ang (ie x = ANG)

Qn: I first like to know if my codes are right. Second, I was wondering what accounts for the difference between random and non-random effects analysis. I always thought random effects analysis are more powerful.

I will follow this up with an email with data attached.

Many thanks for your help.

Regards,
Bernard

**Comment by 0todd0000** [comment]
Hi Bernard,

Thank you for your question. Just to clarify:  "RFT" is usually used to mean "random field theory", but from your question I believe you mean "RFX" or "random effects" analysis?

Note second that this question pertains to general statistics (i.e. random effects modeling).  Please understand that we can only freely support questions that pertain more specifically to the **spm1d** software.

That being said, I'd be pleased to provide a brief response here.  "RFX" generally means that one first computes an effect and then regard that effect as random, hence "random effect".  In other words, the "effect" becomes the dependent variable, rather than the original dependent variable itself. In your example, the RFX analysis uses the dependent variable: "effect of SPEED on Y" and the two-sample test uses the dependent variable: "Y".  Since the dependent variables are different, the conclusions will naturally be different.

Best,
Todd

**Comment by bernard-liew** [comment]
Sorry Todd,

It was a typing mistake, yes RFX, random effects analysis.

Regards,
Bernard
