### ISSUE TITLE
post hoc for n-way repeated measures ANOVA

### ISSUE THREAD

**Issue by zof1985** [0todd0000/spm1d#39]
Hi Todd,

I’m trying to analyse some surface elecromyographic (EMG) data collected during walking trials by SPM1D. The aim is to detect the phase of the gait cycle (if any) at which the same muscles change their activation amplitude because of different ground grades or speeds. I’m going to use the anova2rm function provided by the SPM1D package (the python version) to investigate the grade and speed main and interaction effects. I’m using a repeated measures approach because my participants performed all the grade/speed combination trials (in random order).
My concern is about how to perform post-hoc analyses. I’m not a statistician, but I think that using t-tests with Bonferroni corrected p values would not be a valid approach because of the repeated measures design. Since the SPM1D package actually does not allow for pairwise contrasts / dependent samples t-tests, I would like to perform 1-way repeated measures ANOVA (RM-ANOVA) with Bonferroni corrected p values with each combination of grade and speed used as factor. For instance, to compare the Grade_A-Speed_A combination vs. the Grade_A-Speed_B combination, I would create a factor where these combinations are defined by two values (e.g. 0 and 1 respectively). Then I would perform the 1-way RM-ANOVA to compare these combinations. However, I have never read a paper reporting this approach for post-hoc analyses, therefore I would be very much interested in your opinion about this.
If you have valid alternatives that could suit my analyses I will really appreciate any help.
Thank you in advance for your time and consideration.

Many thanks,
Luca.

**Comment by 0todd0000** [comment]
Dear Luca,

Pairwise contrasts can be performed using paired t tests (**spm1d.stats.ttest_paired**). Note that a one-way RM-ANOVA with two levels is the same as a two-tailed paired t test.

The Bonferroni procedure might be a problem depending on your data;  it is valid under certain circumstances but not under others.

We intend to support more post hoc options in future versions of the software.  For now I'd recommend regarding the two-way ANOVA results as your main results, because these results correspond directly to your (null) hypothesis.  Post hoc analyses simply quailify the main ANOVA result.

Cheers,
Todd

**Comment by zof1985** [comment]
Hi Todd,

Thank you for your answer. You have been very helpful.

Best,
Luca
