### ISSUE TITLE
Testing assumptions

### ISSUE THREAD

**Issue by zof1985** [0todd0000/spm1d#42]
Hi Todd,

I would ask your help in understanding how to analyse some experimental data using the spm1d package.
Lets say that I have time-series corresponding to the accelerations of a body region in one specific spatial direction. These accelerations have been collected from 20 participants, and each participant performed the same test several times varying some experimental conditions in random order. I wish to look at the portions of the actions performed where the experimental conditions differs from each other. Thus, I thought to use paired t-tests between the experimental conditions pairs that I wish to compare. However, because of the multiple statistical tests performed, I would correct the p values for multiple comparisons using the Bonferroni method (or other approaches). The collected data have been interpolated to 101 points, therefore, for each experimental condition, I have a 10 x 101 matrix. Thus, in order to apply a paired t-test between each combination of experimental conditions, should I check the homogeneity of variance and the normality of the distribution for each column of these matrices?
I'm not a statistician, thus I would know if this procedure could be valid and, if not, could you be so kind to provide me another viable approach for the analysis of these data?

Many thanks,
Luca.

**Comment by 0todd0000** [comment]
Hi Luca,

For paired t tests there should be no concerns regarding homogeneity of variance because the variable is y = (yA - yB) where A and B are the two different conditions.  Since A and B are collapsed into one "group" there cannot be different variances in different groups.

For general analyses the procedure you suggest checking variance homogeneity might indeed be useful.  In the SPM literature non-sphericity corrections have been implemented using a slightly different procedure, involving a degrees-of-freedom correction based on an overall non-sphericity estimate. Currently spm1d implements this non-sphericity correction only in the Python version of the software (via the keyword "equal_var") but in spm1d this procedure has only been validated for simple designs including two-sample t tests and one-way ANOVA.  Future versions of the software will implement more comprehensive non-sphericity corrections.

Regards,

Todd

**Comment by zof1985** [comment]
Hi Todd,

Thank you Todd for your clear reply. However, I am still confused about how checking the normality of the distribution. Is there a way you would suggest to do it?

Many thanks,
Luca.

**Comment by 0todd0000** [comment]
Hi Luca,

There are two general approaches to check normality: direct and indirect.

* Direct method:   conduct a parametric normality test (like a K-squared test) by computing the test statistic value at each point in time, then use a random field theory correction to the find the critical value of the test statistic.  If the test statistic trajectory does not exceed the critical value then there is insufficient evidence to reject the null hypothesis of normality.

* Indirect method:  separately conduct parametric and non-parametric tests (e.g. a parametric two-sample t test and a non-parametric t test).  If the results qualitatively agree it would suggest that the parametric approach's assumption of normality is a reasonably good one.  Examples of the indirect approach appear in the paper below, especially in Fig.7:

Pataky, T. C., Vanrenterghem, J., & Robinson, M. A. (2015). Zero- vs. one-dimensional, parametric vs. non-parametric, and confidence interval vs. hypothesis testing procedures in one-dimensional biomechanical trajectory analysis. Journal of Biomechanics, 48(7), 1277–1285. http://doi.org/10.1016/j.jbiomech.2015.02.051




Unfortunately neither the direct nor the indirect approach is implemented in the current version of **spm1d**.  Both be available in future versions.


However, it may be worth noting that normality checking is somewhat moot if you smooth your data.  Smoothing by definition removes outliers and drives the data toward normality.  Thus smoothing  effectively imposes a weak normality constraint on the data.


Cheers,
Todd

**Comment by zof1985** [comment]
Thank you Todd.

You have been very helpful.

Cheers,
Luca.
