### ISSUE TITLE
Aproximated residuals in repeated-measures ANOVA

### ISSUE THREAD

**Issue by m-a-robinson** [0todd0000/spm1d#43]
Hi Todd,
Just a quick question/ clarification about version 0.3.1 release notes which state the following:

WARNING: Repeated-measures ANOVA
 	• IF (a) the data are 1D and (b) there is only one observation per subject and per condition...
 	• THEN inference is approximate, based on approximated residuals.
 	• TO AVOID THIS PROBLEM: use multiple observations per subject per condition, and the same number of observations across all subjects and conditions.

If I interpret this correctly, rather than just providing subject means for each condition I would also include all of the trial data e.g. 5 trials per subject. If there are plenty of subjects and plenty of mean trials within RM conditions, why is having multiple trials necessary/why is inference approximate? 
Is this a 1D rather than 0D issue because trial data would not typically be needed for a 0D SPSS mixed design ANOVA for example?

Thanks in advance,
Regards
Mark

**Comment by 0todd0000** [comment]
Mark!  Inference is approximate because there are no residuals for within-subjects (i.e. repeated measures) models when there is only one observation per subject;  the model contains one parameter per subject per condition (i.e. the mean) so there are no residuals about that parameter.

As you suggest this is not a problem for 0D analysis because all necessary variances can still be estimated. It poses a problem for 1D (and nD) analyses because FWHM estimates require real residuals. **spm1d** v0.3 computes approximate residuals by subtracting individual each subject's mean from their overall between-condition mean. This result is probably quite similar to one obtained using multiple observations per subject per condition, but since mean trajectories tend to be smoother than individual trajectories this approximate approach may overestimate smoothness. There may be a more robust method for estimating FWHM in within-subjects designs, but I'm not sure.

This issue would probably be worth verifying with experimental data:  try running analyses with only subject means, then repeat with all data and check for changes in the estimated FWHM.  I suspect that the FWHM would change a bit but likely not enough to qualitatively affect the results.

Todd
