### ISSUE TITLE
anova3rm

### ISSUE THREAD

**Issue by zof1985** [0todd0000/spm1d#49]
Hi Todd,

I'm using the anova3rm function to investigate the effect of 3 distinct parameters on the EMG activity of one muscle whilst performing a specific exercise (I'm a sport scientist).
The experimental design is rather simple: each participant (n = 20) performs the same exercise 8 times with distinct factors combinations (i.e. load lifted, speed, fatigued/not-fatigued). The order in which the parameters combinations were performed was randomized for each participant. Thus, I have 1 trial for each participant per investigated parameter combination. Since I want to investigate both the main and the interaction effects due to the investigated parameters on the EMG activity of one specific muscle, I decided to use the anova3rm function because all the trials have been performed by the same participants. However, a WARNING message is printed out with the following text:

_`WARNING:`  Only one observation per subject found.  Residuals and inference will be approximate. To avoid approximate residuals: (a) Add multiple observations per subject and per condition, and (b) ensure that all subjects and conditions have the same number of observations.

  if (model.dim == 1) and ( design.check_for_single_responses() ):_

Therefore I wonder if a simple anova3 should be used instead of the anova3rm.

Thanks,
Luca.

**Comment by 0todd0000** [comment]
Hi Luca,

I think anova3rm sounds fine.  The warning message appears when there is only observation per subject because, in this case, there are no model residuals from which smoothness can be estimated. This warning message is unrelated to the test statistic calculation, so the F statistic itself is fine.  The only problem that might arise is if (a) you use only means (instead of all observations) AND (b) the individual observations are much more temporally rough than the means.  Otherwise the results should be practically identical.

Please see issue #43 which briefly discusses this issue, and please let me know if anything remains unclear.

Cheers,

Todd

**Comment by zof1985** [comment]
Hi Todd,

many thanks for the quick and clarifying answer.

Luca.
