### ISSUE TITLE
ROI

### ISSUE THREAD

**Issue by zof1985** [0todd0000/spm1d#50]
Hi Todd,

I'm sorry if this question may appear somehow stupid, but I did not find relevant documentation explaining how to use it. My question is: What is the purpose of the roi analysis? Is it a way to analyse a specific range of the nodes within the analysed time-series? If this is the case, may I use it for post-hoc analyses?

Thanks,
Luca.

**Comment by 0todd0000** [comment]
Hi Luca,

Apologies for the lack of documentation.  We have a paper in peer review which documents use of **spm1d's** ROI functionality in both Python and MATLAB, so if that is accepted we hope it will fill the current documentation gap.

The purpose or ROI analysis is to test _a priori_ hypotheses regarding specific continuum regions.  For example, for theoretical reasons you might be interested in only 0--20% and/or 45--55%.  ROI analyses can test hypotheses regarding single regions, or multiple regions simultaneously.  This allows you to keep your data in its original format, and avoids the need to manually extract regions, and therefore keeps a 1:1 mapping between trial-speific independent variables (subject, condition, etc.) and the dependent variable (a uni- or multi-variate 1D continua).

ROI analysis should generally not be used for _post hoc_ analyses, except perhaps in an exploratory sense, like checking what would have happened had you had a different hypothesis. Without an _a priori_ hypothesis regarding specific regions, ROI results shouldn't be reported.

Here are two references which might be useful:

* Friston, K. J. (1997). Testing for anatomically specified regional effects. Human Brain Mapping, 5(2), 133–136.

* Poldrack, R. A. (2006). Region of interest for fMRI. Social Cognitive and Affective Neuroscience, 2(1):67–70.

Cheers,

Todd

**Comment by zof1985** [comment]
Hi Todd,

Thank you for your quick and clear answer.
According to your answer, I wonder if this approach might be correct then:

1. Let say that I have performed a spm1d 2 way ANOVA. Each factor is binomial and thus post hoc tests about the main effects of the ANOVA are not necessary.
2. However, the interaction effect shows a significant cluster at region 10-30% of the time-series length.

Now my question is: May I use the ROI analysis to specifically investigate the 10-30% region of the time-series by spm1d t-tests and use the results as post-hoc tests? To me, the significant interaction effect in a specific region sounds like an "a priori hypothesis".

Many thanks,
Luca.

**Comment by 0todd0000** [comment]
Hi Luca,

Step 1 is fine but Step 2 is not.  In order to conduct valid ROI analysis you must identify the regions in an _a priori_ sense (i.e. before you conduct the experiment, and before you see the data).  It is similarly invalid to conduct an experiment, plot the data, then decide which portions of the data you want to analyze based on what you observe in the data.  Thus Step 2 is OK if and only if you collect an independent dataset and then use the ROI from the first dataset to analyze the second dataset. 

The alpha-defined critical threshold gets higher as the ROI becomes larger and gets lower as the ROI becomes smaller.  If your original ROI pertains to 0--100%, that is the ROI that must be used in all analyses.

Todd

**Comment by zof1985** [comment]
Hi Todd,

Many thanks for your answer. It has been really useful.

Luca.
