### ISSUE TITLE
Outliers

### ISSUE THREAD

**Issue by zof1985** [0todd0000/spm1d#51]
Hi Todd,

I would like to know your opinion about the outliers detection prior to calculate of the statistical parameteric maps. Particularly, I wonder if the use of a multivariate outliers detection technique such as the minimum covariance determinant approach might be useful in detecting those cases (i.e. rows in the data matrix) that appear significantly different from the others. Accordingly, I would also know your opinion about how to handle the detected outliers, especially within a repeated-measures analysis.

Thanks,
Luca.

**Comment by 0todd0000** [comment]
Hi Luca,

This issue is a bit difficult to respond to directly because outlier detection and exclusion is somewhat controversial and because SPM does not solve any of those controversies.  Nevertheless, univariate and multivariate outlier detection is possible in SPM through typical procedures applied on a point-by-point basis to produce a test statistic continuum (e.g. the Grubbs test statistic).  As long as a test statistic can be computed for 0D univariate or multivariate data then it can be applied directly to 1D univariate and multivariate data.  

There are a number of papers which deal with the outlier issue including:

* Kherif, F., Poline, J. B., Mériaux, S., Benali, H., Flandin, G., & Brett, M. (2003). Group analysis in functional neuroimaging: selecting subjects using similarity measures. NeuroImage, 20(4), 2197-2208.

* Yang, X., Beason-Held, L., Resnick, S. M., & Landman, B. A. (2011). Biological parametric mapping with robust and non-parametric statistics. Neuroimage, 57(2), 423-430.

* Ridgway, G. R., Litvak, V., Flandin, G., Friston, K. J., & Penny, W. D. (2012). The problem of low variance voxels in statistical parametric mapping; a new hat avoids a ‘haircut’. Neuroimage, 59(3), 2131-2141.


My personal feeling is that qualitative detection of outliers is fine provided (a) something clearly went wrong with data collection, and/or (b) you report results both with and without the apparent outliers. If apparent outlier exclusion qualitatively affects your results then you should probably explore and report why. An alternative approach would be to compare parametric and non-paramentric results;  if there are no qualitative differences in the results then the apparent outliers likely do not violate parametric assumptions.  

Cheers,
Todd

**Comment by zof1985** [comment]
Than you very much.
