### ISSUE TITLE
Expert comment on different 1D statistical inference methods

### ISSUE THREAD

**Issue by bernard-liew** [0todd0000/spm1d#62]
Hi Todd,

One of my colleagues was asking me the differences (mainly advantages, disadvantages, limitation) on several 1D statistics methods. I have read the paper you wrote (https://www.ncbi.nlm.nih.gov/pubmed/25817475).

The main methods are

1) SPM
2) Interval testing procedures (https://www.ncbi.nlm.nih.gov/pubmed/26365484)
3) Wavelet anova (https://www.ncbi.nlm.nih.gov/pubmed/23100136)

Side question: Are there methods to analyze 1D signals that are inherently difficult to time register (e.g. standing COP, brain EEG), since unlike gait, it is hard to define time stamps to call it a cycle.

Your continuing help is much appreciated.

Regards,
Bernard

**Comment by 0todd0000** [comment]
Hi Bernard,

As you suggest I think it's best to regard all three techniques as tools, each with their own strengths and weaknesses, and I think those strengths and weaknesses depend largely on one's experimental question;  what makes one technique strong in one situation might make it weak in another.

Unless I'm mistaken (2) above uses functional data analysis (FDA).  In the PubMed paper above there's a brief comparison of FDA and SPM in Appendix B.  To summarize that Appendix, FDA can be used for a considerably broader spectrum of analyses than can SPM, but for classical hypothesis testing SPM may be a slightly more natural choice because its randomness model (through random field theory) is simpler.

More generally, the fundamental difference amongst the methods is how the data are modeled.  SPM regards experimental variance as 1D Gaussian, and parameterizes that variance using just two parameters:  (1) experimental degrees of freedom and (2) the ratio of the continuum size to its smoothness.  (Statistical non-parametric mapping relaxes that assumption, and actually converges quite closely to some FDA techniques).  FDA much more flexibility models variance through a set of parameterized basis functions;  the functions can powerfully model arbitrary data, but more parameters are required to do so.  Wavelet analysis similarly employs parameterized models and can similarly model arbitrary data.

SPM's main advantage is thus that it can rapidly generate predictions (i.e. p values) for arbitrary experiments. The main advantage of FDA and wavelet analysis is that they much more flexibly model arbitrary 1D data, and thus are far superior to SPM in terms of describing 1D shapes (e.g. mean curves).  I confess that I am unfamiliar with the relative merits of FDA vs. wavelet analysis.

Regarding registration:  I think you're exactly right.  It can be difficult or even impossible to register 1D segments in long-term tasks like quite standing, quiet sitting, etc.  SPM requires registered data, but FDA and wavelet analysis don't.

Todd

**Comment by bernard-liew** [comment]
Thank you Todd for the detailed explanation.

Regards,
Bernard
