### ISSUE TITLE
Normality check

### ISSUE THREAD

**Issue by zof1985** [0todd0000/spm1d#65]
Hi Todd,

A reviewer asked me about the check of the normality of my data for anova3rm analysis. Briefly, he would like to see a single p value rather than a p value for each point of my interpolated (101 points) timeseries. Therefore I would know your opinion about using some multivariate normality tests like the Henze-Zirkler’s test or similar ([ref.](https://cran.r-project.org/web/packages/MVN/vignettes/MVN.pdf)).

Many thanks,
Luca.

**Comment by 0todd0000** [comment]
Hi Luca,

Mark, Jos and I are coincidentally preparing a paper right now precisely on that issue, and we've got three different multivariate normality tests implemented including the Henze-Zirkler test.  All three will be available in **spm1d** in the next few months.  However, one problem is that there is really no good test of multivariate normality;  the tests work generally well on 0D data but their small imperfections become magnified when extending the tests to 1D.

So instead of explicit normality testing I'd recommend running non-parametric analyses, which are available in the current version of **spm1d**.  Insofar as the parametric and non-parametric results qualitatively agree one can conclude that the parametric approach's assumption of normality is a reasonable one.  In this case explicit normality testing is redundant.  If, however, the results qualitatively disagree then the non-parametric results should be used because they are valid for all distributions, normal or otherwise.  

Todd

**Comment by zof1985** [comment]
Hi Todd,

As always. Your answers are very helpful.

Many thanks,
Luca
