### ISSUE TITLE
How to report SPM in a manuscript - clarifications to reviewers

### ISSUE THREAD

**Issue by depierie** [0todd0000/spm1d#90]
Hi Todd,

I'm posting this here as I think it might be useful for other users who have recently started using SPM1d and are trying to publish their results. 

I've recently submitted a manuscript and described the use of SPM as follow: 
[...] For each linear regression, an output test statistic SPM{t} was evaluated at each point in the time series. Significance level was set at α=0.01, and the corresponding SPM{t*} critical threshold was calculated based on the temporal smoothness of the input data through Random Field Theory. Finally, the probability that similar supra-threshold regions would have occurred from equally smooth random waveforms was calculated. [...]

Among the reviewers' comments, I've been asked to include additional details, and I'm not sure how to address this in a satisfactory way:

Comment1:  The description of the statistical analysis is too brief. It is, for example, unclear whether or
not the assumptions underlying the methods are were fulfilled [...] "Describe statistical methods with enough detail to enable a knowledgeable reader with access to the original data to judge its appropriateness for the study and to verify the reported results".

Comment2: Please define the used symbols, e.g. <alpha>; and SPM{t}.

For the latter, I've found this formula in the tutorial slides, however I'm not sure how it can be explained synthetically in the context of a paper.

![image](https://user-images.githubusercontent.com/10941676/48953378-f4953080-ef45-11e8-8755-270eb0133e85.png)

Would you have any recommendation on which additional details could be provided in the description above? I thought I followed the general indications that were suggested at the SPM1d tutorials, and the examples of previously published articles but this appear not to be sufficient.

Hopefully this will help spreading the understanding of SPM as a methodology to the larger scientific community and facilitates the publication of future work.

Thank you very much for your help, again!
Enrico

**Comment by 0todd0000** [comment]
Hi Enrico,

> "Describe statistical methods with enough detail to enable a knowledgeable reader with access to the original data to judge its appropriateness for the study and to verify the reported results"

One way to satisfy this requirement is to: (a) provide your data and script(s) to reviewers, then (b) clarify that the software package is open source. That way reviewers will be able to reproduce your results exactly, and they will also be able to go through the source code if they have any concerns.

Regarding assumptions:  you could state that the assumptions are the same as a typical t test:

1. Random sampling
2. Homologous data
3. Normally distributed data.

There are no explicit tests for the first two assumptions. The second assumption can be tested implicitly using different registration schemes (e.g. linear vs. nonlinear time normalization), but **spm1d** currently does not support nonlinear registration.  I think it would be sufficient to cite other papers for the homologous data assumption ---  linear time normalization is fairly standard across the literature, and mean continua are often computed and reported, implying that homologous data assumption is presumed to be satisfied. 

There are explicit tests for the third assumption in **spm1d.stats.normality**. You could also implicitly test the third assumption by re-running the test using nonparametric inference, available in **spm1d.stats.nonparam**; if the parametric and nonparametric results do not differ qualitatively, then the assumption of normality is a reasonable one.

A few symbol notes:

- "SPM", by itself, refers to the methodology: statistical parametric mapping. 

- "SPM{z}" is the test statistic continuum, where "z" is the test statistic. For the t and F test statistics, the symbol becomes SPM{t} and SPM{F}, respectively. So it may be clearer to state that the t statistic (or the t value) was computed at each point in time, thereby forming an SPM{t}.

- "SPM{t*}"  Instead of this I'd recommend using just "t*".  The "SPM{ }" part implies a continuum, but t* is a single scalar value that does not change across the continuum.  "SPM{t}" is OK because the t value can change across the continuum.

Cheers,

Todd

**Comment by depierie** [comment]
Hi Todd,
thank you very much for your answer, extremely helpful and clear as usual!

I've run the non-parametric test ( similarly to the example nonparam/1d/ex_regression.py) and it showed very good agreement for all the parametric regression analyses I've run. I will mention this in the manuscript and refer to your paper : "Pataky TC, Vanrenterghem J, Robinson MA. Zero-vs. one-dimensional, parametric vs. non-parametric, and confidence interval vs. hypothesis testing procedures in one-dimensional biomechanical trajectory analysis. Journal of biomechanics. 2015 May 1;48(7):1277-85."
I've seen that you're discussing also the homology of the data in this paper, so I will refer to that as well.

I have one additional question: one reviewer also pointed out that despite running regression analyses, we reported our results as correlations (e.g. "The regression analyses revealed a significant positive correlation between BMI and HCF"), which would imply a cause-effect relation.
Do you think that describing these findings with "statistically significant positive/negative relationships" would be more appropriate for an exploratory study without cause/effect assumptions? Or is the term relationship too vague?

Thank you again.

Cheers,
Enrico

**Comment by 0todd0000** [comment]
Hi Enrico, sorry for the delay!
Correlation never implies causation, so I would avoid "cause-effect" when describing correlation results.  "Statistically significant positive/negative linear correlation" might be clearest.
Todd
